@startuml SISTEMA DE URNA ELETRONICA - DIAGRAMA DE CASOS DE USO
skinparam actorstyle awesome
left to right direction

rectangle "Sistema de Urna Eletrônica" {
  
  '--- Primeira coluna:
  together {
    actor "Administrador" as admin
    package "Gestão da Eleição" {
      (Criar Eleição) as CE
      (Apurar Eleição) as AE
      (Cadastrar Chapa) as CC
    }
    actor "Eleitor" as eleitor
  }

  '--- Segunda coluna:
  together {
    package "Participação do Eleitor" {
      (Verificar-se) as VER
      (Emitir Voto) as EV
    }
    actor "Calculador de Resultados" as calc
    package "Resultados" {
      (Apurar Votos) as AV
      (Declarar Vencedor) as DV
    }
  }

  '--- Relações de atores
  admin --> CE
  admin --> AE
  admin --> CC

  eleitor --> VER
  eleitor --> EV

  calc --> AV
  calc --> DV

  '--- Relações de dependência
  EV .> VER : <<include>>
  AE .> CE : <<extend>>
  AV .> AE : <<include>>
  DV .> AV : <<include>>
}
@enduml
