@startuml SISTEMA DE URNA ELETRONICA
skinparam actorstyle awesome

left to right direction

actor "Administrador" as admin
actor "Eleitor" as eleitor
actor "Calculador de Resultados" as calc

rectangle "Sistema de Urna Eletrônica" {
  
  package "Gestão da Eleição" {
    (Criar Eleição) as CE
    (Fechar Eleição) as FE
    (Cadastrar Chapa) as CC
  }

  package "Participação do Eleitor" {
    (Verificar-se) as VER
    (Emitir Voto) as EV
  }

  package "Resultados" {
    (Calcular Totais) as CT
    (Obter Vencedor) as OV
    (Exportar Resultados) as ER
  }
}

'--- Relações de atores
admin --> CE
admin --> FE
admin --> CC

eleitor --> VER
eleitor --> EV

calc --> CT
calc --> OV
calc --> ER

'--- Relações de dependência
EV .> VER : <<include>> // Emitir Voto inclui \nVerificar-se
FE .> CE : <<extend>>  // Fechar Eleição só ocorre \napós Criar Eleição
CT .> FE : <<include>> // Calcular Totais depende de Eleição fechada
OV .> CT : <<include>> // Obter Vencedor depende \nde Calcular Totais
ER <. CT : <<include>> // Exportar resultados \ndepende de Calcular totais

@enduml
