@startuml
left to right direction

rectangle "Sistema de Urna Eletrônica" {

    class Eleicao {
        -id: int
        -titulo: string
        -data_inicio: datetime
        -data_fim: datetime

        +esta_ativa(): bool
        +ja_iniciou(): bool
        +ja_terminou(): bool
        +iniciar()
        +finalizar()
    }

    class Cargo {
        -id: int
        -nome: string
        -descricao: string
    }

    class Candidato {
        -id: int
        -nome: string
        -int cargo_id
    }

    class Chapa{
        -id: int
        -nome: string
        -slogan: string
        -logo: picture[?]
    }

    class Eleitor {
        -matricula: int
        -nome: string
        -curso: string
        -data_nasc: datetime
        -email_institucional: string
        -verificado: bool

        +verificar()
    }

    class Voto {
        -id: int
        -chapa_id: int
    }

    class Cedula {
        -id: int
        -eleicao_id: int
        -eleitor_id: int
        -votado_em: datetime
        -e_valida: bool

        +registrar_voto(escolha)
    }


    class Administrador {
        -id: int
        -usuario: string
        -senha: string

        +criar_eleicao()
        +fechar_eleicao()
        +cadastrar_candidato()
    }

    class CalculadorResultados {
        +calcular_totais(eleicao_id)
        +obter_vencedor()
        +exportar_resultados(eleicao_id) : (?)
    }

    Chapa "1..*" *-- "1..*" Cargo : > Contem
    Cargo "1..*" *-- "1..1" Candidato : Candidata-se <
    Eleicao "1..0" *-- "*..*" Chapa : > Possui
    Eleitor "1..1" -- "0..1" Cedula : > Emite
    Cedula "1..1" -- "1..1" Voto : > Contém
    Administrador "1..*" *-- "1..1" Eleicao : > Gerencia
    CalculadorResultados "1..*" --> "1..1" Eleicao : > Calcula
    Administrador "1..1" *-  "1..*" Chapa : > Cadastra
    Eleicao "1..* " *--  "1..1 " Voto: > Contém
}

@enduml