@startuml SISTEMA DE URNA ELETRONICA
skinparam actorstyle awesome

left to right direction

rectangle "Sistema de Urna Eletrônica" {
  actor "Administrador" as admin
  actor "Eleitor" as eleitor
  actor "Calculador de Resultados" as calc

  package "Gestão da Eleição" {
    (Criar Eleição) as CE
    (Apurar Eleição) as AE
    (Cadastrar Chapa) as CC
  }

  package "Participação do Eleitor" {
    (Verificar-se) as VER
    (Emitir Voto) as EV
  }

  package "Resultados" {
    (Apurar Votos) as AV
    (Declarar Vencedor) as DV
  }
  '--- Relações de atores
  admin --> CE
  admin --> AE
  admin --> CC

  eleitor --> VER
  eleitor --> EV

  calc --> AV
  calc --> DV
  '--- Relações de dependência
  EV .> VER : <<include>> // Emitir Voto inclui \nVerificar-se
  AE .> CE : <<extend>>  // Apurar Eleição só ocorre \napós Criar Eleição
  AV .> AE : <<include>> // Apurar Votos depende de Apurar Eleição
  DV .> AV : <<include>> // Declarar Vencedor depende de Apurar Votos
}
@enduml
