--@startuml SISTEMA DE URNA ELETRONICA

class Eleicao {
        +id: int
        +titulo: string
        +data_inicio: datetime
        +data_fim: datetime

        +esta_ativa(): bool
        +ja_iniciou(): bool
        +ja_terminou(): bool
        +iniciar()
        +finalizar()
    }

    class Cargo {
        +id: int
        +nome: string
        +descricao: string
    }

    class Candidato {
        +id: int
        +nome: string
        +int cargo_id
    }

    class Eleitor {
        +matricula: int
        +nome: string
        +curso: string
        +data_nasc: datetime
        +email_institucional: string
        +verificado: bool
        +registrar()
        +verificar()
    }

    class Voto {
        +id: int
        +cargo_id: int
        +candidato_id: int
    }

    class Cedula {
        +id: int
        +eleicao_id: int
        +eleitor_id: int
        +votado_em: datetime
        +e_valida: bool
        +registrar_voto(escolhas)
    }


    class Administrador {
        +id: int
        +usuario: string
        +senha: string
        +criar_eleicao()
        +fechar_eleicao()
        +cadastrar_candidato()
    }

    class CalculadorResultados {
        +calcular_totais(eleicao_id)
        +obter_vencedor()
        +exportar_resultados(eleicao_id) : (?)
    }

    Eleicao "1..*" o-- "1..*" Cargo : Contem
    Cargo "1..*" o-- "1..1" Candidato : Tem
    Eleicao "1..0" -o "*..*" Candidato : Possui
    Eleitor "1..1" -- "0..1" Cedula : emite
    Cedula "1..1" -- "1..1" Voto : contém
    Administrador "1..*" *-- "1..1" Eleicao : Gerencia
    CalculadorResultados "1..*" --> "1..1" Eleicao : Calcula
    Administrador "1..*" *-  "1..*" Candidato : Cadastra
    Eleicao "1..*" *-  "1..1" Voto: Contém

@enduml