name: Python application

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.3"

    - name: Instalação de Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Lint with flake8 (only in 'app' folder)
      run: |
        flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Merge Branch
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: main 
          github_token: ${{ github.token }}
